services:
  - type: web
    name: driveguard-ai
    env: docker
    region: ohio
    plan: free
    dockerCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT api:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
